version: '3.6'
services:
  nginx:
    image: nginx:latest
    ports: []
#      - '80:80'
#      - '443:443'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./src:/var/www/html:rw,cached
      - ./certs:/etc/certs
    depends_on:
      - php-fpm
    restart: on-failure

  php-fpm:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html:rw,cached
      - ./php-fpm/config/main.ini:/usr/local/etc/php/conf.d/php.ini
      - ./php-fpm/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_NAME=
      - WORDPRESS_DB_HOST=
      - WORDPRESS_DB_USER=
      - WORDPRESS_DB_PASSWORD=
    restart: on-failure

  composer:
    image: composer/composer
    working_dir: /var/www/html
    restart: 'no'
    volumes:
      - ./src:/var/www/html:rw,cached


### Mailhog ################################################
  mailhog:
    image: mailhog/mailhog
    ports: []
#      - "1025:1025"
#      - "8025:8025"
    restart: on-failure
